# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phage_name', models.CharField(default='none', max_length=30)),
                ('phage_host_name', models.CharField(default='none', max_length=30)),
                ('phage_isolator_name', models.CharField(default='none', max_length=30)),
                ('phage_experimenter_name', models.CharField(default='none', max_length=30)),
                ('phage_CPT_id', models.CharField(default='none', max_length=100)),
                ('phage_isolator_loc', models.CharField(default='none', max_length=5000)),
                ('phage_submitted_user', models.CharField(default='none', max_length=5000)),
                ('phage_submitted_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('phage_all_links', models.CharField(default='none', max_length=5000)),
                ('phage_lab', models.CharField(default='A', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phagename', models.CharField(default='none', max_length=30)),
                ('testkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PhageName', to='core.PhageData')),
            ],
        ),
    ]
