# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phage_name', models.CharField(default='none', max_length=30)),
                ('phage_host_name', models.CharField(default='none', max_length=30)),
                ('phage_isolator_name', models.CharField(default='none', max_length=30)),
                ('phage_experimenter_name', models.CharField(default='none', max_length=30)),
                ('phage_CPT_id', models.CharField(default='none', max_length=100)),
                ('phage_isolator_loc', models.CharField(default='none', max_length=5000)),
            ],
        ),
    ]
