# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phagedata',
            old_name='phage_lab',
            new_name='phage_lab1',
        ),
    ]
