# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 00:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171122_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='none', max_length=100)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.CharField(default='none', max_length=100)),
                ('short_name', models.CharField(default='none', max_length=100)),
                ('full_name', models.CharField(default='none', max_length=5000)),
                ('methods', models.CharField(default='none', max_length=5000)),
                ('results', models.CharField(default='none', max_length=5000)),
                ('expkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PName', to='core.PhageData')),
            ],
        ),
    ]
