# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 06:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_experimentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsolationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='none', max_length=100)),
                ('location', models.CharField(default='none', max_length=100)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(default='none', max_length=100)),
                ('isokey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iso_phageName', to='core.PhageData')),
            ],
        ),
    ]
